# ============================================================
# ПОЛНОЕ МЕНЮ НА 30 ДНЕЙ
# ============================================================

BASE_MENU = {
    1: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Овсяная каша', 'dry_weight': '40 г', 'ready_weight': 170, 'calories': 220, 'water': 120, 'salt': 5, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл кипятка, варить 5 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '10 г', 'ready_weight': 10, 'calories': 55, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яблоко печёное', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 80, 'water': 100, 'salt': 2, 'sugar': 8, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Клюква', 'dry_weight': '30 г', 'ready_weight': 30, 'calories': 15, 'water': 0, 'salt': 0, 'sugar': 2, 'fiber': 1, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Мёд', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 16, 'water': 0, 'salt': 0, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Борщ', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 180, 'water': 280, 'salt': 180, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 20 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Курица', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат с авокадо', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 140, 'water': 120, 'salt': 10, 'sugar': 2, 'fiber': 3, 'recipe': 'Нарезать, заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': 'Залить кипятком.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Хлебец ц/з', 'dry_weight': '20 г', 'ready_weight': 20, 'calories': 55, 'water': 5, 'salt': 15, 'sugar': 0, 'fiber': 2, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Треска', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 165, 'water': 110, 'salt': 50, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Кабачок тушёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 55, 'water': 170, 'salt': 10, 'sugar': 4, 'fiber': 2, 'recipe': 'Тушить 10 мин.'},
    ],
    2: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Омлет из 2 яиц', 'dry_weight': '100 г', 'ready_weight': 120, 'calories': 160, 'water': 70, 'salt': 85, 'sugar': 1, 'fiber': 0, 'recipe': 'Жарить на сухой сковороде.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Огурец свежий', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Хлебец ц/з', 'dry_weight': '25 г', 'ready_weight': 25, 'calories': 65, 'water': 5, 'salt': 20, 'sugar': 0, 'fiber': 3, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Семечки тыквенные', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Солянка домашняя', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 170, 'water': 290, 'salt': 170, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат с авокадо', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 150, 'water': 130, 'salt': 10, 'sugar': 3, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Котлета куриная паровая', 'dry_weight': '100 г', 'ready_weight': 130, 'calories': 190, 'water': 80, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Рис отварной', 'dry_weight': '40 г', 'ready_weight': 120, 'calories': 150, 'water': 50, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 120 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Брокколи на пару', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 65, 'water': 180, 'salt': 15, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    3: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Рисовая каша', 'dry_weight': '40 г', 'ready_weight': 200, 'calories': 240, 'water': 140, 'salt': 3, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Груша печёная', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 85, 'water': 110, 'salt': 2, 'sugar': 9, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Суп-пюре из цветной капусты', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 120, 'water': 270, 'salt': 40, 'sugar': 3, 'fiber': 5, 'recipe': 'Пюрировать блендером.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Куриная грудка', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат с авокадо', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 130, 'water': 120, 'salt': 8, 'sugar': 2, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Хек на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 150, 'water': 110, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Перловка', 'dry_weight': '40 г', 'ready_weight': 150, 'calories': 190, 'water': 80, 'salt': 3, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл воды, варить 25 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Стручковая фасоль', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 70, 'water': 160, 'salt': 12, 'sugar': 3, 'fiber': 5, 'recipe': 'Тушить 10 мин.'},
    ],
    4: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Лепёшка бездрожжевая', 'dry_weight': '30 г муки', 'ready_weight': 120, 'calories': 200, 'water': 40, 'salt': 10, 'sugar': 1, 'fiber': 3, 'recipe': 'Запечь 10 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Творожный сыр 5%', 'dry_weight': '30 г', 'ready_weight': 30, 'calories': 60, 'water': 15, 'salt': 50, 'sugar': 1, 'fiber': 0, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Индейка варёная', 'dry_weight': '80 г', 'ready_weight': 80, 'calories': 110, 'water': 70, 'salt': 20, 'sugar': 0, 'fiber': 1, 'recipe': 'Отварить 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Куриный суп-пюре', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 140, 'water': 290, 'salt': 50, 'sugar': 3, 'fiber': 4, 'recipe': 'Пюрировать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Куриная голень', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 230, 'water': 90, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат капустный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 110, 'water': 130, 'salt': 12, 'sugar': 4, 'fiber': 5, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Судак на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 160, 'water': 110, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Кабачок тушёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 55, 'water': 170, 'salt': 10, 'sugar': 4, 'fiber': 2, 'recipe': 'Тушить 10 мин.'},
    ],
    5: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яичница из 2 яиц', 'dry_weight': '100 г', 'ready_weight': 150, 'calories': 170, 'water': 80, 'salt': 90, 'sugar': 1, 'fiber': 0, 'recipe': 'Жарить без масла.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Помидор свежий', 'dry_weight': '120 г', 'ready_weight': 120, 'calories': 22, 'water': 110, 'salt': 8, 'sugar': 3, 'fiber': 2, 'recipe': 'Нарезать.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Хлебец ц/з', 'dry_weight': '25 г', 'ready_weight': 25, 'calories': 65, 'water': 5, 'salt': 20, 'sugar': 0, 'fiber': 3, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Клюква', 'dry_weight': '30 г', 'ready_weight': 30, 'calories': 15, 'water': 0, 'salt': 0, 'sugar': 2, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Рыбный суп', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 150, 'water': 280, 'salt': 160, 'sugar': 3, 'fiber': 3, 'recipe': 'Варить 10 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат зелёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 90, 'water': 140, 'salt': 10, 'sugar': 2, 'fiber': 3, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Куриная грудка запечённая', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Запечь 20 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Рис отварной', 'dry_weight': '40 г', 'ready_weight': 120, 'calories': 150, 'water': 50, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 120 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Брокколи на пару', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 65, 'water': 180, 'salt': 15, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    6: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 170, 'calories': 200, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '10 г', 'ready_weight': 10, 'calories': 55, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яблоко печёное', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 80, 'water': 100, 'salt': 2, 'sugar': 8, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Огурец', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Грибной суп', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 110, 'water': 280, 'salt': 40, 'sugar': 3, 'fiber': 4, 'recipe': 'Варить 10 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Сосиска домашняя', 'dry_weight': '70 г', 'ready_weight': 70, 'calories': 120, 'water': 50, 'salt': 45, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 10 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат овощной', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 100, 'water': 140, 'salt': 10, 'sugar': 4, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Минтай на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 140, 'water': 110, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Цветная капуста', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 60, 'water': 180, 'salt': 12, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    7: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Творог 5%', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 180, 'water': 100, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Ягоды', 'dry_weight': '80 г', 'ready_weight': 80, 'calories': 35, 'water': 70, 'salt': 2, 'sugar': 6, 'fiber': 2, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Семена чиа', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 25, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 2, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Борщ', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 180, 'water': 280, 'salt': 180, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 20 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Курица', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат с авокадо', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 130, 'water': 120, 'salt': 8, 'sugar': 2, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Хлебец ц/з', 'dry_weight': '20 г', 'ready_weight': 20, 'calories': 55, 'water': 5, 'salt': 15, 'sugar': 0, 'fiber': 2, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Роллы домашние', 'dry_weight': 'Рис 40, курица 80, огурец 100', 'ready_weight': 150, 'calories': 190, 'water': 70, 'salt': 45, 'sugar': 2, 'fiber': 2, 'recipe': 'Завернуть в нори.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Огурец свежий', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
    ],
    8: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Овсяная каша', 'dry_weight': '40 г', 'ready_weight': 170, 'calories': 220, 'water': 120, 'salt': 5, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл кипятка, варить 5 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '10 г', 'ready_weight': 10, 'calories': 55, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яблоко печёное', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 80, 'water': 100, 'salt': 2, 'sugar': 8, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Солянка', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 170, 'water': 290, 'salt': 170, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат капустный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 110, 'water': 130, 'salt': 12, 'sugar': 4, 'fiber': 5, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Индейка запечённая', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 210, 'water': 80, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'Запечь 20 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Кабачок тушёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 55, 'water': 170, 'salt': 10, 'sugar': 4, 'fiber': 2, 'recipe': 'Тушить 10 мин.'},
    ],
    9: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Омлет из 2 яиц', 'dry_weight': '100 г', 'ready_weight': 120, 'calories': 160, 'water': 70, 'salt': 85, 'sugar': 1, 'fiber': 0, 'recipe': 'Жарить на сухой сковороде.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Огурец', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Хлебец ц/з', 'dry_weight': '25 г', 'ready_weight': 25, 'calories': 65, 'water': 5, 'salt': 20, 'sugar': 0, 'fiber': 3, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Суп-пюре из брокколи', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 120, 'water': 270, 'salt': 40, 'sugar': 3, 'fiber': 6, 'recipe': 'Пюрировать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Куриная грудка', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат зелёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 90, 'water': 140, 'salt': 10, 'sugar': 2, 'fiber': 3, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Скумбрия запечённая', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 240, 'water': 80, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'Запечь 20 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Рис отварной', 'dry_weight': '40 г', 'ready_weight': 120, 'calories': 150, 'water': 50, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 120 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Стручковая фасоль', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 70, 'water': 160, 'salt': 12, 'sugar': 3, 'fiber': 5, 'recipe': 'Тушить 10 мин.'},
    ],
    10: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Рисовая каша', 'dry_weight': '40 г', 'ready_weight': 200, 'calories': 240, 'water': 140, 'salt': 3, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Груша печёная', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 85, 'water': 110, 'salt': 2, 'sugar': 9, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Куриный суп с лапшой', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 160, 'water': 280, 'salt': 20, 'sugar': 3, 'fiber': 2, 'recipe': 'Варить 5 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Сосиска домашняя', 'dry_weight': '70 г', 'ready_weight': 70, 'calories': 120, 'water': 50, 'salt': 45, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 10 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат овощной', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 100, 'water': 140, 'salt': 10, 'sugar': 4, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Зразы куриные', 'dry_weight': '100 г', 'ready_weight': 130, 'calories': 190, 'water': 80, 'salt': 40, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Брокколи на пару', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 65, 'water': 180, 'salt': 15, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    11: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Лепёшка бездрожжевая', 'dry_weight': '30 г муки', 'ready_weight': 120, 'calories': 200, 'water': 40, 'salt': 10, 'sugar': 1, 'fiber': 3, 'recipe': 'Запечь 10 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Творожный сыр 5%', 'dry_weight': '30 г', 'ready_weight': 30, 'calories': 60, 'water': 15, 'salt': 50, 'sugar': 1, 'fiber': 0, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Индейка варёная', 'dry_weight': '80 г', 'ready_weight': 80, 'calories': 110, 'water': 70, 'salt': 20, 'sugar': 0, 'fiber': 1, 'recipe': 'Отварить 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Суп из чечевицы', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 180, 'water': 260, 'salt': 15, 'sugar': 4, 'fiber': 8, 'recipe': 'Варить 20 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Индейка отварная', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 210, 'water': 80, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат с авокадо', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 130, 'water': 120, 'salt': 8, 'sugar': 2, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Треска на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 165, 'water': 110, 'salt': 50, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Перловка', 'dry_weight': '40 г', 'ready_weight': 150, 'calories': 190, 'water': 80, 'salt': 3, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл воды, варить 25 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Цветная капуста', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 60, 'water': 180, 'salt': 12, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    12: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яичница из 2 яиц', 'dry_weight': '100 г', 'ready_weight': 150, 'calories': 170, 'water': 80, 'salt': 90, 'sugar': 1, 'fiber': 0, 'recipe': 'Жарить без масла.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Помидор', 'dry_weight': '120 г', 'ready_weight': 120, 'calories': 22, 'water': 110, 'salt': 8, 'sugar': 3, 'fiber': 2, 'recipe': 'Нарезать.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Хлебец ц/з', 'dry_weight': '25 г', 'ready_weight': 25, 'calories': 65, 'water': 5, 'salt': 20, 'sugar': 0, 'fiber': 3, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Огурец', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Борщ', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 180, 'water': 280, 'salt': 180, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 20 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Курица', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат капустный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 110, 'water': 130, 'salt': 12, 'sugar': 4, 'fiber': 5, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Куриная голень запечённая', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 230, 'water': 90, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'Запечь 25 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Кабачок тушёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 55, 'water': 170, 'salt': 10, 'sugar': 4, 'fiber': 2, 'recipe': 'Тушить 10 мин.'},
    ],
    13: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 170, 'calories': 200, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '10 г', 'ready_weight': 10, 'calories': 55, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яблоко печёное', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 80, 'water': 100, 'salt': 2, 'sugar': 8, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Клюква', 'dry_weight': '30 г', 'ready_weight': 30, 'calories': 15, 'water': 0, 'salt': 0, 'sugar': 2, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Солянка', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 170, 'water': 290, 'salt': 170, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат зелёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 90, 'water': 140, 'salt': 10, 'sugar': 2, 'fiber': 3, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Судак на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 160, 'water': 110, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Рис отварной', 'dry_weight': '40 г', 'ready_weight': 120, 'calories': 150, 'water': 50, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 120 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Брокколи на пару', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 65, 'water': 180, 'salt': 15, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    14: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Овсяная каша', 'dry_weight': '40 г', 'ready_weight': 170, 'calories': 220, 'water': 120, 'salt': 5, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл кипятка, варить 5 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '10 г', 'ready_weight': 10, 'calories': 55, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яблоко печёное', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 80, 'water': 100, 'salt': 2, 'sugar': 8, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Грибной суп', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 110, 'water': 280, 'salt': 40, 'sugar': 3, 'fiber': 4, 'recipe': 'Варить 10 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Сосиска домашняя', 'dry_weight': '70 г', 'ready_weight': 70, 'calories': 120, 'water': 50, 'salt': 45, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 10 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат овощной', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 100, 'water': 140, 'salt': 10, 'sugar': 4, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Роллы домашние', 'dry_weight': 'Рис 40, авокадо 40, огурец 100', 'ready_weight': 150, 'calories': 190, 'water': 70, 'salt': 40, 'sugar': 2, 'fiber': 3, 'recipe': 'Завернуть в нори.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Огурец свежий', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
    ],
    15: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Омлет из 2 яиц', 'dry_weight': '100 г', 'ready_weight': 120, 'calories': 160, 'water': 70, 'salt': 85, 'sugar': 1, 'fiber': 0, 'recipe': 'Жарить на сухой сковороде.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Огурец', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Хлебец ц/з', 'dry_weight': '25 г', 'ready_weight': 25, 'calories': 65, 'water': 5, 'salt': 20, 'sugar': 0, 'fiber': 3, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Суп-пюре из кабачков', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 120, 'water': 270, 'salt': 40, 'sugar': 3, 'fiber': 6, 'recipe': 'Пюрировать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Куриная грудка', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат с авокадо', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 130, 'water': 120, 'salt': 8, 'sugar': 2, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Минтай на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 140, 'water': 110, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Кабачок тушёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 55, 'water': 170, 'salt': 10, 'sugar': 4, 'fiber': 2, 'recipe': 'Тушить 10 мин.'},
    ],
    16: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Рисовая каша', 'dry_weight': '40 г', 'ready_weight': 200, 'calories': 240, 'water': 140, 'salt': 3, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Груша печёная', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 85, 'water': 110, 'salt': 2, 'sugar': 9, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Огурец', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Борщ', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 180, 'water': 280, 'salt': 180, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 20 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Курица', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат зелёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 90, 'water': 140, 'salt': 10, 'sugar': 2, 'fiber': 3, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Котлета куриная', 'dry_weight': '100 г', 'ready_weight': 130, 'calories': 190, 'water': 80, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Рис отварной', 'dry_weight': '40 г', 'ready_weight': 120, 'calories': 150, 'water': 50, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 120 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Брокколи на пару', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 65, 'water': 180, 'salt': 15, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    17: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Лепёшка бездрожжевая', 'dry_weight': '30 г муки', 'ready_weight': 120, 'calories': 200, 'water': 40, 'salt': 10, 'sugar': 1, 'fiber': 3, 'recipe': 'Запечь 10 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Творожный сыр 5%', 'dry_weight': '30 г', 'ready_weight': 30, 'calories': 60, 'water': 15, 'salt': 50, 'sugar': 1, 'fiber': 0, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Индейка варёная', 'dry_weight': '80 г', 'ready_weight': 80, 'calories': 110, 'water': 70, 'salt': 20, 'sugar': 0, 'fiber': 1, 'recipe': 'Отварить 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Клюква', 'dry_weight': '30 г', 'ready_weight': 30, 'calories': 15, 'water': 0, 'salt': 0, 'sugar': 2, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Солянка', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 170, 'water': 290, 'salt': 170, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат капустный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 110, 'water': 130, 'salt': 12, 'sugar': 4, 'fiber': 5, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Хек на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 150, 'water': 110, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Перловка', 'dry_weight': '40 г', 'ready_weight': 150, 'calories': 190, 'water': 80, 'salt': 3, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл воды, варить 25 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Цветная капуста', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 60, 'water': 180, 'salt': 12, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    18: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Овсяная каша', 'dry_weight': '40 г', 'ready_weight': 170, 'calories': 220, 'water': 120, 'salt': 5, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл кипятка, варить 5 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '10 г', 'ready_weight': 10, 'calories': 55, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яблоко печёное', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 80, 'water': 100, 'salt': 2, 'sugar': 8, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Рыбный суп', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 150, 'water': 280, 'salt': 160, 'sugar': 3, 'fiber': 3, 'recipe': 'Варить 10 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат овощной', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 100, 'water': 140, 'salt': 10, 'sugar': 4, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Говядина тушёная', 'dry_weight': '80 г', 'ready_weight': 80, 'calories': 180, 'water': 70, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'Тушить 40 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Стручковая фасоль', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 70, 'water': 160, 'salt': 12, 'sugar': 3, 'fiber': 5, 'recipe': 'Тушить 10 мин.'},
    ],
    19: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яичница из 2 яиц', 'dry_weight': '100 г', 'ready_weight': 150, 'calories': 170, 'water': 80, 'salt': 90, 'sugar': 1, 'fiber': 0, 'recipe': 'Жарить без масла.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Помидор', 'dry_weight': '120 г', 'ready_weight': 120, 'calories': 22, 'water': 110, 'salt': 8, 'sugar': 3, 'fiber': 2, 'recipe': 'Нарезать.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Хлебец ц/з', 'dry_weight': '25 г', 'ready_weight': 25, 'calories': 65, 'water': 5, 'salt': 20, 'sugar': 0, 'fiber': 3, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Куриный суп-пюре', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 140, 'water': 290, 'salt': 50, 'sugar': 3, 'fiber': 4, 'recipe': 'Пюрировать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Индейка отварная', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 210, 'water': 80, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат с авокадо', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 130, 'water': 120, 'salt': 8, 'sugar': 2, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Скумбрия запечённая', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 240, 'water': 80, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'Запечь 20 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Рис отварной', 'dry_weight': '40 г', 'ready_weight': 120, 'calories': 150, 'water': 50, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 120 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Кабачок тушёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 55, 'water': 170, 'salt': 10, 'sugar': 4, 'fiber': 2, 'recipe': 'Тушить 10 мин.'},
    ],
    20: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Рисовая каша', 'dry_weight': '40 г', 'ready_weight': 200, 'calories': 240, 'water': 140, 'salt': 3, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Груша печёная', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 85, 'water': 110, 'salt': 2, 'sugar': 9, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Огурец', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Суп-пюре из цветной капусты', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 120, 'water': 270, 'salt': 40, 'sugar': 3, 'fiber': 5, 'recipe': 'Пюрировать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Куриная голень', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 230, 'water': 90, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат зелёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 90, 'water': 140, 'salt': 10, 'sugar': 2, 'fiber': 3, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Судак на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 160, 'water': 110, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Брокколи на пару', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 65, 'water': 180, 'salt': 15, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    21: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 170, 'calories': 200, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '10 г', 'ready_weight': 10, 'calories': 55, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яблоко печёное', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 80, 'water': 100, 'salt': 2, 'sugar': 8, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Клюква', 'dry_weight': '30 г', 'ready_weight': 30, 'calories': 15, 'water': 0, 'salt': 0, 'sugar': 2, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Борщ', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 180, 'water': 280, 'salt': 180, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 20 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Курица', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат капустный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 110, 'water': 130, 'salt': 12, 'sugar': 4, 'fiber': 5, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Роллы домашние', 'dry_weight': 'Рис 40, курица 80, огурец 100', 'ready_weight': 150, 'calories': 190, 'water': 70, 'salt': 45, 'sugar': 2, 'fiber': 2, 'recipe': 'Завернуть в нори.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Огурец свежий', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
    ],
    22: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Омлет из 2 яиц', 'dry_weight': '100 г', 'ready_weight': 120, 'calories': 160, 'water': 70, 'salt': 85, 'sugar': 1, 'fiber': 0, 'recipe': 'Жарить на сухой сковороде.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Огурец', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Хлебец ц/з', 'dry_weight': '25 г', 'ready_weight': 25, 'calories': 65, 'water': 5, 'salt': 20, 'sugar': 0, 'fiber': 3, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Солянка', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 170, 'water': 290, 'salt': 170, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат с авокадо', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 130, 'water': 120, 'salt': 8, 'sugar': 2, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Куриная грудка запечённая', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Запечь 20 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Рис отварной', 'dry_weight': '40 г', 'ready_weight': 120, 'calories': 150, 'water': 50, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 120 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Кабачок тушёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 55, 'water': 170, 'salt': 10, 'sugar': 4, 'fiber': 2, 'recipe': 'Тушить 10 мин.'},
    ],
    23: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Рисовая каша', 'dry_weight': '40 г', 'ready_weight': 200, 'calories': 240, 'water': 140, 'salt': 3, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Груша печёная', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 85, 'water': 110, 'salt': 2, 'sugar': 9, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Суп-пюре из брокколи', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 120, 'water': 270, 'salt': 40, 'sugar': 3, 'fiber': 6, 'recipe': 'Пюрировать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Котлета куриная', 'dry_weight': '100 г', 'ready_weight': 130, 'calories': 190, 'water': 80, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат зелёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 90, 'water': 140, 'salt': 10, 'sugar': 2, 'fiber': 3, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Треска на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 165, 'water': 110, 'salt': 50, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Стручковая фасоль', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 70, 'water': 160, 'salt': 12, 'sugar': 3, 'fiber': 5, 'recipe': 'Тушить 10 мин.'},
    ],
    24: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Овсяная каша', 'dry_weight': '40 г', 'ready_weight': 170, 'calories': 220, 'water': 120, 'salt': 5, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл кипятка, варить 5 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '10 г', 'ready_weight': 10, 'calories': 55, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яблоко печёное', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 80, 'water': 100, 'salt': 2, 'sugar': 8, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Куриный суп с лапшой', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 160, 'water': 280, 'salt': 20, 'sugar': 3, 'fiber': 2, 'recipe': 'Варить 5 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Сосиска домашняя', 'dry_weight': '70 г', 'ready_weight': 70, 'calories': 120, 'water': 50, 'salt': 45, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 10 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат овощной', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 100, 'water': 140, 'salt': 10, 'sugar': 4, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Зразы куриные', 'dry_weight': '100 г', 'ready_weight': 130, 'calories': 190, 'water': 80, 'salt': 40, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Брокколи на пару', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 65, 'water': 180, 'salt': 15, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    25: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 170, 'calories': 200, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '10 г', 'ready_weight': 10, 'calories': 55, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яблоко печёное', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 80, 'water': 100, 'salt': 2, 'sugar': 8, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Клюква', 'dry_weight': '30 г', 'ready_weight': 30, 'calories': 15, 'water': 0, 'salt': 0, 'sugar': 2, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Рыбный суп', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 150, 'water': 280, 'salt': 160, 'sugar': 3, 'fiber': 3, 'recipe': 'Варить 10 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат с авокадо', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 130, 'water': 120, 'salt': 8, 'sugar': 2, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Индейка запечённая', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 210, 'water': 80, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'Запечь 20 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Перловка', 'dry_weight': '40 г', 'ready_weight': 150, 'calories': 190, 'water': 80, 'salt': 3, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл воды, варить 25 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Цветная капуста', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 60, 'water': 180, 'salt': 12, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    26: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Омлет из 2 яиц', 'dry_weight': '100 г', 'ready_weight': 120, 'calories': 160, 'water': 70, 'salt': 85, 'sugar': 1, 'fiber': 0, 'recipe': 'Жарить на сухой сковороде.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Огурец', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Хлебец ц/з', 'dry_weight': '25 г', 'ready_weight': 25, 'calories': 65, 'water': 5, 'salt': 20, 'sugar': 0, 'fiber': 3, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Грибной суп', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 110, 'water': 280, 'salt': 40, 'sugar': 3, 'fiber': 4, 'recipe': 'Варить 10 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Куриная голень', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 230, 'water': 90, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат капустный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 110, 'water': 130, 'salt': 12, 'sugar': 4, 'fiber': 5, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Хек на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 150, 'water': 110, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Рис отварной', 'dry_weight': '40 г', 'ready_weight': 120, 'calories': 150, 'water': 50, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 120 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Кабачок тушёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 55, 'water': 170, 'salt': 10, 'sugar': 4, 'fiber': 2, 'recipe': 'Тушить 10 мин.'},
    ],
    27: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Рисовая каша', 'dry_weight': '40 г', 'ready_weight': 200, 'calories': 240, 'water': 140, 'salt': 3, 'sugar': 0, 'fiber': 1, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Груша печёная', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 85, 'water': 110, 'salt': 2, 'sugar': 9, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Суп-пюре из кабачков', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 120, 'water': 270, 'salt': 40, 'sugar': 3, 'fiber': 6, 'recipe': 'Пюрировать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Куриная грудка', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат зелёный', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 90, 'water': 140, 'salt': 10, 'sugar': 2, 'fiber': 3, 'recipe': 'Заправить маслом.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Минтай на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 140, 'water': 110, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Брокколи на пару', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 65, 'water': 180, 'salt': 15, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    28: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Овсяная каша', 'dry_weight': '40 г', 'ready_weight': 170, 'calories': 220, 'water': 120, 'salt': 5, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл кипятка, варить 5 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '10 г', 'ready_weight': 10, 'calories': 55, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яблоко печёное', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 80, 'water': 100, 'salt': 2, 'sugar': 8, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Тыквенные семечки', 'dry_weight': '5 г', 'ready_weight': 5, 'calories': 28, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Борщ', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 180, 'water': 280, 'salt': 180, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 20 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Курица', 'dry_weight': '130 г', 'ready_weight': 130, 'calories': 215, 'water': 80, 'salt': 30, 'sugar': 0, 'fiber': 0, 'recipe': 'Отварить.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат с авокадо', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 130, 'water': 120, 'salt': 8, 'sugar': 2, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Роллы домашние', 'dry_weight': 'Рис 40, курица 80, огурец 100', 'ready_weight': 150, 'calories': 190, 'water': 70, 'salt': 45, 'sugar': 2, 'fiber': 2, 'recipe': 'Завернуть в нори.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Огурец свежий', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
    ],
    29: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Омлет из 2 яиц', 'dry_weight': '100 г', 'ready_weight': 120, 'calories': 160, 'water': 70, 'salt': 85, 'sugar': 1, 'fiber': 0, 'recipe': 'Жарить на сухой сковороде.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Помидор', 'dry_weight': '120 г', 'ready_weight': 120, 'calories': 22, 'water': 110, 'salt': 8, 'sugar': 3, 'fiber': 2, 'recipe': 'Нарезать.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Хлебец ц/з', 'dry_weight': '25 г', 'ready_weight': 25, 'calories': 65, 'water': 5, 'salt': 20, 'sugar': 0, 'fiber': 3, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Кефир 1%', 'dry_weight': '200 мл', 'ready_weight': 200, 'calories': 80, 'water': 180, 'salt': 60, 'sugar': 4, 'fiber': 0, 'recipe': ''},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Солянка', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 170, 'water': 290, 'salt': 170, 'sugar': 4, 'fiber': 4, 'recipe': 'Варить 15 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат овощной', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 100, 'water': 140, 'salt': 10, 'sugar': 4, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Котлета куриная', 'dry_weight': '100 г', 'ready_weight': 130, 'calories': 190, 'water': 80, 'salt': 35, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 180, 'calories': 210, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 5, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Цветная капуста', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 60, 'water': 180, 'salt': 12, 'sugar': 2, 'fiber': 4, 'recipe': 'На пару 10 мин.'},
    ],
    30: [
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Гречка', 'dry_weight': '40 г', 'ready_weight': 170, 'calories': 200, 'water': 90, 'salt': 3, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл воды, варить 15 мин.'},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Тыквенные семечки', 'dry_weight': '10 г', 'ready_weight': 10, 'calories': 55, 'water': 0, 'salt': 0, 'sugar': 0, 'fiber': 1, 'recipe': ''},
        {'meal': 'Завтрак', 'time': '08:30', 'dish': 'Яблоко печёное', 'dry_weight': '1 шт (150 г)', 'ready_weight': 150, 'calories': 80, 'water': 100, 'salt': 2, 'sugar': 8, 'fiber': 3, 'recipe': 'Запечь 15 мин.'},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Творог 5%', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 120, 'water': 70, 'salt': 40, 'sugar': 3, 'fiber': 0, 'recipe': ''},
        {'meal': 'Перекус', 'time': '11:00', 'dish': 'Огурец', 'dry_weight': '100 г', 'ready_weight': 100, 'calories': 15, 'water': 90, 'salt': 5, 'sugar': 2, 'fiber': 1, 'recipe': 'Нарезать.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Рыбный суп', 'dry_weight': '350 мл', 'ready_weight': 350, 'calories': 150, 'water': 280, 'salt': 160, 'sugar': 3, 'fiber': 3, 'recipe': 'Варить 10 мин.'},
        {'meal': 'Обед', 'time': '14:00', 'dish': 'Салат с авокадо', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 130, 'water': 120, 'salt': 8, 'sugar': 2, 'fiber': 4, 'recipe': 'Нарезать, заправить.'},
        {'meal': 'Перекус', 'time': '17:00', 'dish': 'Отвар шиповника', 'dry_weight': '10 г', 'ready_weight': 150, 'calories': 10, 'water': 150, 'salt': 2, 'sugar': 0, 'fiber': 0, 'recipe': ''},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Судак на пару', 'dry_weight': '150 г', 'ready_weight': 150, 'calories': 160, 'water': 110, 'salt': 55, 'sugar': 0, 'fiber': 0, 'recipe': 'На пару 15 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Перловка', 'dry_weight': '40 г', 'ready_weight': 150, 'calories': 190, 'water': 80, 'salt': 3, 'sugar': 0, 'fiber': 4, 'recipe': 'Залить 150 мл воды, варить 25 мин.'},
        {'meal': 'Ужин', 'time': '19:30', 'dish': 'Стручковая фасоль', 'dry_weight': '200 г', 'ready_weight': 200, 'calories': 70, 'water': 160, 'salt': 12, 'sugar': 3, 'fiber': 5, 'recipe': 'Тушить 10 мин.'},
    ],
}

# ============================================================
# ФУНКЦИЯ ПОЛУЧЕНИЯ МЕНЮ С АВТОПЕРЕЗАПУСКОМ И СНИЖЕНИЕМ КАЛОРИЙНОСТИ
# ============================================================
def get_menu_day(day_num, current_weight):
    """
    Возвращает меню для указанного дня с учётом:
    - автоперезапуска цикла (если день > 30 — начинаем сначала)
    - снижения калорийности в зависимости от веса
    """
    # Автоперезапуск: если день больше 30 — начинаем сначала
    if day_num > 30:
        day_num = ((day_num - 1) % 30) + 1
    
    # Базовое меню для этого дня
    menu = BASE_MENU.get(day_num, [])
    
    # Расчёт коэффициента снижения калорийности
    # Исходный вес 89 кг → калорийность 1500 ккал
    # Целевой вес 60 кг → калорийность 1200 ккал
    max_loss = 29  # от 89 до 60 кг
    current_loss = max(0, 89 - current_weight)  # сколько уже сбросили
    loss_factor = 1 - (current_loss / max_loss) * 0.3  # от 1.0 до 0.7
    
    # Ограничиваем, чтобы калорийность не опускалась ниже 1200 ккал
    base_calories = 1500  # исходная калорийность при 89 кг
    target_calories = max(1200, base_calories * loss_factor)
    calorie_factor = target_calories / base_calories
    
    # Применяем коэффициент к каждому блюду
    corrected_menu = []
    for item in menu:
        new_item = dict(item)
        # Корректируем калорийность
        new_item['calories'] = int(item['calories'] * calorie_factor)
        # Пропорционально уменьшаем вес готового блюда
        new_item['ready_weight'] = int(item['ready_weight'] * calorie_factor)
        # Воду, соль, сахар и клетчатку тоже уменьшаем пропорционально
        new_item['water'] = int(item['water'] * calorie_factor)
        new_item['salt'] = int(item['salt'] * calorie_factor)
        new_item['sugar'] = int(item['sugar'] * calorie_factor)
        new_item['fiber'] = int(item['fiber'] * calorie_factor)
        corrected_menu.append(new_item)
    
    return corrected_menu
